
import FullStackProvider from "@/provider/FullStackProvider";
import "@repo/ui/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { JSX } from "react";
import '../lib/orpc.server' // for pre-rendering

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "campus",
  description: "Generated by create turbo",
};

import "@syncfusion/ej2-base/styles/material.css";
import "@syncfusion/ej2-icons/styles/material.css";
import "@syncfusion/ej2-buttons/styles/material.css";
import "@syncfusion/ej2-splitbuttons/styles/material.css";
import "@syncfusion/ej2-inputs/styles/material.css";
import "@syncfusion/ej2-lists/styles/material.css";
import "@syncfusion/ej2-navigations/styles/material.css";
import "@syncfusion/ej2-popups/styles/material.css";
import "@syncfusion/ej2-dropdowns/styles/material.css";
import "@syncfusion/ej2-grids/styles/material.css";
import "@syncfusion/ej2-react-spreadsheet/styles/material.css";
import SyncProvider from "@/context/syncProvider";


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <FullStackProvider>
          <SyncProvider>

            {children}
          </SyncProvider>
        </FullStackProvider>
      </body>
    </html>
  );
}
