import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
// import "./globals.css";

import "@repo/ui/globals.css";
import FullStackProvider from "@/provider/FullStackProvider";
import { JSX } from "react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "campus",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <FullStackProvider>{children}</FullStackProvider>
      </body>
    </html>
  );
}
