export const EditorCanvasDefaultCardTypes = {
  FilterNode: { type: 'Action', description: 'Filter data' },
  InputImage: { type: 'Action', description: 'Send a notification to slack' },
  TextInputNode: { type: 'Action', description: 'Send a notification to slack' },
  CamelCaseNode: { type: 'Action', description: 'Send a notification to slack' },
  OutputNode2: { type: 'Action', description: 'Send a notification to slack' },
  LowercaseNode: { type: 'Action', description: 'Send a notification to slack' },
  FilterCsvNode: {
    description: 'Send a notification to slack',
    type: 'Action',
  },
  baseNodebar: {
    description: 'Send a notification to slack',
    type: 'Action',
  },
  baseNodeFull: { description: 'Send a notification to slack', type: 'Action' },
  InputFile: { description: 'Send a notification to slack', type: 'Action' },
  InputText: { description: 'Send a notification to slack', type: 'Action' },
  baseOutput: { description: 'Send a notification to slack', type: 'Action' },
  Email: { description: 'Send an email', type: 'Action' },
  Condition: { description: 'Conditional logic', type: 'Condition' },
  AI: { description: 'AI processing', type: 'Action' },
  Slack: { description: 'Send a notification to slack', type: 'Action' },
  'Google Drive': { description: 'Google Drive integration', type: 'Action' },
  Notion: { description: 'Notion integration', type: 'Action' },
  'Custom Webhook': { description: 'Custom webhook', type: 'Action' },
  'Google Calendar': { description: 'Google Calendar integration', type: 'Action' },
  Trigger: { description: 'Workflow trigger', type: 'Trigger' },
  Action: { description: 'Workflow action', type: 'Action' },
  Wait: { description: 'Wait/delay', type: 'Action' },
}